set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports d[7] ]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports d[6] ]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports d[5] ]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports d[4] ]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports d[3] ]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports d[2] ]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports d[1] ]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports d[0] ]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports clk ]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports wen ]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports wsel[2] ]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports wsel[1]]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports wsel[0]]
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports q[7] ]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports q[6] ]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports q[5] ]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports q[4] ]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports q[3] ]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports q[2] ]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports q[1] ]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports q[0] ]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports clrn ]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports rsel[1]  ]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports rsel[0] ]