set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports data_o[7] ]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports data_o[6] ]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports data_o[5] ]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports data_o[4] ]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports data_o[3] ]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports data_o[2] ]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports data_o[1] ]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports data_o[0] ]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports en_i[2] ]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports en_i[1] ]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports en_i[0] ]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports data_i[2] ]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports data_i[1] ]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports data_i[0] ]

